########################################################################################################################
##              EL ENRUTAMIENTO EN SYMFONY 4 FUNCIONA BAJO UN PATRÓN DE JERARQUÍAS. LAS MISMAS SON:                   ##
##              · Annotations (Sistema de rutas por anotaciones en las funciones de los controladores)                ##
##              · YAML (Sistema de rutas por archivo de texto plano)                                                  ##
##              · XML (Sistema de rutas por archivo de texto plano)                                                   ##
##              · PHP (Sistema de rutas por archivo de texto plano)                                                   ##
########################################################################################################################
# Logout
logout:
  path: /logout

# Errors
error_404:
  path: /{route}
  controller: App\Controller\SecurityController::error_404
  requirements:
    route: '.+'